// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/MsPersistence.proto

package mspersistence

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetDataServiceClient is the client API for GetDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetDataServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type getDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetDataServiceClient(cc grpc.ClientConnInterface) GetDataServiceClient {
	return &getDataServiceClient{cc}
}

func (c *getDataServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/mspersistence.GetDataService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetDataServiceServer is the server API for GetDataService service.
// All implementations must embed UnimplementedGetDataServiceServer
// for forward compatibility
type GetDataServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedGetDataServiceServer()
}

// UnimplementedGetDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGetDataServiceServer struct {
}

func (UnimplementedGetDataServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGetDataServiceServer) mustEmbedUnimplementedGetDataServiceServer() {}

// UnsafeGetDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetDataServiceServer will
// result in compilation errors.
type UnsafeGetDataServiceServer interface {
	mustEmbedUnimplementedGetDataServiceServer()
}

func RegisterGetDataServiceServer(s grpc.ServiceRegistrar, srv GetDataServiceServer) {
	s.RegisterService(&GetDataService_ServiceDesc, srv)
}

func _GetDataService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetDataServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mspersistence.GetDataService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetDataServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetDataService_ServiceDesc is the grpc.ServiceDesc for GetDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mspersistence.GetDataService",
	HandlerType: (*GetDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GetDataService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/MsPersistence.proto",
}
